-- =============================================================================
-- Quasar.io — Oda örnekleri & matchmaking (300 yarıçap eşiği)
-- SQL Editor'da schema.sql sonrası çalıştırın.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) TABLOLAR
-- -----------------------------------------------------------------------------

create table if not exists public.game_room_instances (
  id uuid primary key default gen_random_uuid(),
  room_type text not null,
  instance_number int not null,
  leader_radius int not null default 25,
  real_player_count int not null default 0,
  status text not null default 'open',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz,
  constraint game_room_instances_room_type_check
    check (room_type in ('normal', 'elite', 'unique')),
  constraint game_room_instances_status_check
    check (status in ('open', 'closed')),
  constraint game_room_instances_player_count_check
    check (real_player_count >= 0 and real_player_count <= 20),
  constraint game_room_instances_leader_radius_check
    check (leader_radius >= 0 and leader_radius <= 550),
  unique (room_type, instance_number)
);

create table if not exists public.game_room_members (
  id bigint generated by default as identity primary key,
  room_instance_id uuid not null
    references public.game_room_instances(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default timezone('utc', now()),
  left_at timestamptz
);

create unique index if not exists game_room_members_active_user_key
  on public.game_room_members (user_id)
  where left_at is null;

create index if not exists game_room_instances_matchmaking_idx
  on public.game_room_instances (room_type, status, leader_radius, instance_number)
  where status = 'open';

alter table public.game_room_instances enable row level security;
alter table public.game_room_members enable row level security;

drop policy if exists "Oda örneklerini herkes görebilir" on public.game_room_instances;
create policy "Oda örneklerini herkes görebilir"
  on public.game_room_instances for select
  using (true);

drop policy if exists "Üyeler kendi kayıtlarını görebilir" on public.game_room_members;
create policy "Üyeler kendi kayıtlarını görebilir"
  on public.game_room_members for select
  using (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- 2) RPC — ODADAN AYRIL
-- -----------------------------------------------------------------------------

create or replace function public.leave_game_room(p_room_instance_id uuid default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_member record;
begin
  if v_user_id is null then
    raise exception 'not authenticated';
  end if;

  for v_member in
    select id, room_instance_id
    from public.game_room_members
    where user_id = v_user_id
      and left_at is null
      and (p_room_instance_id is null or room_instance_id = p_room_instance_id)
    for update
  loop
    update public.game_room_members
    set left_at = timezone('utc', now())
    where id = v_member.id;

    update public.game_room_instances
    set
      real_player_count = greatest(0, real_player_count - 1),
      updated_at = timezone('utc', now())
    where id = v_member.room_instance_id;
  end loop;
end;
$$;

grant execute on function public.leave_game_room(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- 3) RPC — ODAYA KATIL (300 yarıçap altı, max 20 oyuncu)
-- -----------------------------------------------------------------------------

create or replace function public.join_game_room(p_room_type text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_room_type text := lower(trim(p_room_type));
  v_room public.game_room_instances%rowtype;
  v_next_instance int;
  v_stale_before timestamptz := timezone('utc', now()) - interval '3 minutes';
begin
  if v_user_id is null then
    raise exception 'not authenticated';
  end if;

  if v_room_type = 'simple' then
    raise exception 'training_room_no_matchmaking';
  end if;

  if v_room_type not in ('normal', 'elite', 'unique') then
    raise exception 'invalid room_type';
  end if;

  perform public.leave_game_room(null);

  perform pg_advisory_xact_lock(hashtext('join_game_room_' || v_room_type));

  update public.game_room_members grm
  set left_at = timezone('utc', now())
  from public.game_room_instances gri
  where grm.room_instance_id = gri.id
    and gri.room_type = v_room_type
    and grm.left_at is null
    and coalesce(gri.updated_at, gri.created_at) < v_stale_before;

  update public.game_room_instances gri
  set
    status = 'closed',
    real_player_count = 0,
    leader_radius = 25,
    updated_at = timezone('utc', now())
  where gri.room_type = v_room_type
    and gri.status = 'open'
    and (
      not exists (
        select 1
        from public.game_room_members grm
        where grm.room_instance_id = gri.id
          and grm.left_at is null
      )
      or coalesce(gri.updated_at, gri.created_at) < v_stale_before
    );

  update public.game_room_instances gri
  set
    real_player_count = sub.cnt,
    updated_at = timezone('utc', now())
  from (
    select grm.room_instance_id, count(*)::int as cnt
    from public.game_room_members grm
    where grm.left_at is null
    group by grm.room_instance_id
  ) as sub
  where gri.id = sub.room_instance_id
    and gri.room_type = v_room_type
    and gri.status = 'open'
    and gri.real_player_count != sub.cnt;

  select *
  into v_room
  from public.game_room_instances gri
  where gri.room_type = v_room_type
    and gri.status = 'open'
    and gri.leader_radius < 300
    and gri.real_player_count < 20
    and coalesce(gri.updated_at, gri.created_at) >= v_stale_before
    and exists (
      select 1
      from public.game_room_members grm
      where grm.room_instance_id = gri.id
        and grm.left_at is null
    )
  order by gri.instance_number asc
  limit 1
  for update;

  if not found then
    select *
    into v_room
    from public.game_room_instances
    where room_type = v_room_type
      and status = 'closed'
    order by instance_number asc
    limit 1
    for update;

    if found then
      delete from public.game_room_members
      where room_instance_id = v_room.id;

      update public.game_room_instances
      set
        status = 'open',
        leader_radius = 25,
        real_player_count = 0,
        updated_at = timezone('utc', now())
      where id = v_room.id
      returning * into v_room;
    else
      select coalesce(max(instance_number), 0) + 1
      into v_next_instance
      from public.game_room_instances
      where room_type = v_room_type;

      insert into public.game_room_instances (
        room_type,
        instance_number,
        real_player_count,
        leader_radius,
        status
      )
      values (v_room_type, v_next_instance, 0, 25, 'open')
      returning * into v_room;
    end if;
  end if;

  insert into public.game_room_members (room_instance_id, user_id)
  values (v_room.id, v_user_id);

  update public.game_room_instances
  set
    real_player_count = real_player_count + 1,
    updated_at = timezone('utc', now())
  where id = v_room.id
  returning * into v_room;

  return json_build_object(
    'room_instance_id', v_room.id,
    'instance_number', v_room.instance_number,
    'real_player_count', v_room.real_player_count,
    'leader_radius', v_room.leader_radius
  );
end;
$$;

grant execute on function public.join_game_room(text) to authenticated;

-- -----------------------------------------------------------------------------
-- 4) RPC — LİDER YARIÇAP GÜNCELLE
-- -----------------------------------------------------------------------------

create or replace function public.update_room_leader_radius(
  p_room_instance_id uuid,
  p_leader_radius int
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  if p_leader_radius < 0 or p_leader_radius > 550 then
    raise exception 'invalid leader_radius';
  end if;

  update public.game_room_instances gri
  set
    leader_radius = greatest(gri.leader_radius, p_leader_radius),
    updated_at = timezone('utc', now())
  where gri.id = p_room_instance_id
    and gri.status = 'open'
    and exists (
      select 1
      from public.game_room_members grm
      where grm.room_instance_id = p_room_instance_id
        and grm.user_id = auth.uid()
        and grm.left_at is null
    );
end;
$$;

grant execute on function public.update_room_leader_radius(uuid, int) to authenticated;

-- -----------------------------------------------------------------------------
-- 5) RPC — ODAYI KAPAT (evren bittiğinde)
-- -----------------------------------------------------------------------------

create or replace function public.close_game_room(p_room_instance_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  if not exists (
    select 1
    from public.game_room_members grm
    where grm.room_instance_id = p_room_instance_id
      and grm.user_id = auth.uid()
      and grm.left_at is null
  ) then
    raise exception 'not an active room member';
  end if;

  update public.game_room_members
  set left_at = timezone('utc', now())
  where room_instance_id = p_room_instance_id
    and left_at is null;

  update public.game_room_instances
  set
    status = 'closed',
    real_player_count = 0,
    leader_radius = 25,
    updated_at = timezone('utc', now())
  where id = p_room_instance_id
    and status = 'open';
end;
$$;

grant execute on function public.close_game_room(uuid) to authenticated;
