-- =============================================================================
-- Quasar.io — Supabase SQL (SQL Editor'da tek seferde çalıştırın)
-- Proje: https://supabase.com/dashboard → SQL → New query → Run
--
-- UYARI (güvenlik): Bu dosya yalnızca yeşil saha bootstrap'tır.
-- Canlı / prod kurulumda MUTLAKA sırayla security + economy migration'larını
-- da uygulayın (migration_economy_security.sql, migration_security_m1_m4.sql,
-- migration_security_m5.sql … migration_security_high_fixes.sql,
-- migration_security_medium_fixes.sql, migration_security_high_anon_sim_mint.sql).
-- Yalnızca schema.sql ile bırakmak ekonomi / PII yüzeylerini zayıf bırakır.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) TABLOLAR
-- -----------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamptz,
  username text,
  avatar_url text,
  diamonds int not null default 20,
  games_won int not null default 0,
  active_skin text not null default 'default',
  -- Skill tree (also applied via migration_skill_tree.sql on existing DBs)
  peak_diamonds int not null default 20,
  skill_tree jsonb not null default '{}'::jsonb
);

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  username text,
  max_mass int not null default 0,
  room_type text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz
);

-- Upsert için (Flutter: leaderboard.upsert onConflict: user_id)
create unique index if not exists leaderboard_user_id_key
  on public.leaderboard (user_id);

create table if not exists public.user_skins (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  skin_id text not null,
  created_at timestamptz not null default timezone('utc', now())
);

-- Aynı kozmetiğin iki kez satın alınmasını engelle
create unique index if not exists user_skins_user_skin_key
  on public.user_skins (user_id, skin_id);

-- Mevcut kurulumda eksik sütunları ekle (ADIM 10)
alter table public.leaderboard
  add column if not exists username text,
  add column if not exists room_type text,
  add column if not exists updated_at timestamptz;

-- -----------------------------------------------------------------------------
-- 2) ROW LEVEL SECURITY (RLS) — sıkı baseline (açık SELECT / istemci skor yazma yok)
-- -----------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.leaderboard enable row level security;
alter table public.user_skins enable row level security;

-- profiles: yalnızca kendi satırı (herkese açık profil scrape kapalı)
drop policy if exists "Profilleri herkes görebilir" on public.profiles;
drop policy if exists "Kullanıcı kendi profilini görebilir" on public.profiles;
create policy "Kullanıcı kendi profilini görebilir"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Kullanıcılar kendi profillerini güncelleyebilir" on public.profiles;
create policy "Kullanıcılar kendi profillerini güncelleyebilir"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

revoke select on public.profiles from anon;

-- leaderboard: doğrudan istemci yazma yok — save_leaderboard_score RPC kullan
drop policy if exists "Skorları herkes görebilir" on public.leaderboard;
drop policy if exists "Kullanıcılar kendi skorlarını ekleyebilir" on public.leaderboard;
drop policy if exists "Kullanıcılar kendi skorlarını güncelleyebilir" on public.leaderboard;
drop policy if exists "Kullanıcı kendi skorunu görebilir" on public.leaderboard;
create policy "Kullanıcı kendi skorunu görebilir"
  on public.leaderboard for select
  to authenticated
  using (auth.uid() = user_id);

revoke select, insert, update, delete on public.leaderboard from anon, public;
revoke insert, update, delete on public.leaderboard from authenticated;
grant select on public.leaderboard to authenticated;

-- user_skins
drop policy if exists "Görünümleri sahipleri görebilir" on public.user_skins;
create policy "Görünümleri sahipleri görebilir"
  on public.user_skins for select
  using (auth.uid() = user_id);

drop policy if exists "Kullanıcılar görünüm satın alabilir" on public.user_skins;
create policy "Kullanıcılar görünüm satın alabilir"
  on public.user_skins for insert
  with check (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- 3) YENİ KULLANICI → OTOMATİK PROFİL (Google OAuth sonrası)
-- -----------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, avatar_url, diamonds, games_won, active_skin, updated_at)
  values (
    new.id,
    left(
      trim(
        coalesce(
          new.raw_user_meta_data->>'full_name',
          new.raw_user_meta_data->>'name',
          'Cosmic Void'
        )
      ),
      12
    ),
    new.raw_user_meta_data->>'avatar_url',
    20,
    0,
    'default',
    timezone('utc', now())
  )
  on conflict (id) do nothing;

  insert into public.user_skins (user_id, skin_id)
  values (new.id, 'default')
  on conflict (user_id, skin_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- 4) RPC — GLOBAL SIRALAMA (Profile menü)
-- -----------------------------------------------------------------------------

create or replace function public.get_user_rank(user_uuid uuid)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  user_position int;
begin
  select position into user_position
  from (
    select
      id,
      row_number() over (order by diamonds desc, games_won desc, updated_at desc nulls last) as position
    from public.profiles
  ) ranked
  where id = user_uuid;

  return coalesce(user_position, 0);
end;
$$;

grant execute on function public.get_user_rank(uuid) to authenticated;
-- anon'a vermeyin: sıralama/PII probing yüzeyi.

-- -----------------------------------------------------------------------------
-- 5) RPC — GÜVENLİ SKOR KAYDI (isteğe bağlı, hile önleme)
--    Flutter şu an doğrudan upsert kullanıyor; ileride RPC'ye geçilebilir.
-- -----------------------------------------------------------------------------

create or replace function public.save_leaderboard_score(
  p_max_mass int,
  p_room_type text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  if p_max_mass < 0 or p_max_mass > 500 then
    raise exception 'invalid max_mass';
  end if;

  select username into v_username
  from public.profiles
  where id = auth.uid();

  insert into public.leaderboard (user_id, username, max_mass, room_type, updated_at)
  values (
    auth.uid(),
    coalesce(v_username, 'Traveler'),
    p_max_mass,
    p_room_type,
    timezone('utc', now())
  )
  on conflict (user_id) do update set
    max_mass = greatest(public.leaderboard.max_mass, excluded.max_mass),
    username = excluded.username,
    room_type = excluded.room_type,
    updated_at = excluded.updated_at;
end;
$$;

grant execute on function public.save_leaderboard_score(int, text) to authenticated;

-- -----------------------------------------------------------------------------
-- 6) RPC — MAÇ SONUCU (yerleştirme ödülü / eleme cezası, elmas asla 0 altına inmez)
--    Basit: 1.=+3, 2.=+2, 3.=+1; eleme=0
--    Normal: 1.=+5, 2.=+3, 3.=+2; eleme=-1 (floor 0)
--    Elite:  1.=+10, 2.=+6, 3.=+4; eleme=-2 (floor 0)
--    Unique: 1.=+15, 2.=+10, 3.=+5; eleme=-3 (floor 0)
-- -----------------------------------------------------------------------------

create or replace function public.apply_match_result(
  p_room_type text default 'normal',
  p_placement int default null,
  p_eliminated boolean default false
)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
  v_delta int := 0;
  v_won int := 0;
  v_new_diamonds int;
  v_room text := lower(coalesce(p_room_type, 'normal'));
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  if coalesce(p_eliminated, false) then
    v_delta := case v_room
      when 'simple' then 0
      when 'elite' then -2
      when 'unique' then -3
      else -1
    end;
  else
    case v_room
      when 'simple' then
        if p_placement = 1 then
          v_delta := 3;
          v_won := 1;
        elsif p_placement = 2 then
          v_delta := 2;
        elsif p_placement = 3 then
          v_delta := 1;
        end if;
      when 'elite' then
        if p_placement = 1 then
          v_delta := 10;
          v_won := 1;
        elsif p_placement = 2 then
          v_delta := 6;
        elsif p_placement = 3 then
          v_delta := 4;
        end if;
      when 'unique' then
        if p_placement = 1 then
          v_delta := 15;
          v_won := 1;
        elsif p_placement = 2 then
          v_delta := 10;
        elsif p_placement = 3 then
          v_delta := 5;
        end if;
      else
        -- normal
        if p_placement = 1 then
          v_delta := 5;
          v_won := 1;
        elsif p_placement = 2 then
          v_delta := 3;
        elsif p_placement = 3 then
          v_delta := 2;
        end if;
    end case;
  end if;

  if v_delta = 0 and v_won = 0 then
    select diamonds into v_new_diamonds
    from public.profiles
    where id = auth.uid();
    return coalesce(v_new_diamonds, 0);
  end if;

  update public.profiles
  set
    diamonds = greatest(0, diamonds + v_delta),
    games_won = games_won + v_won,
    updated_at = timezone('utc', now())
  where id = auth.uid()
  returning diamonds into v_new_diamonds;

  return coalesce(v_new_diamonds, 0);
end;
$$;

grant execute on function public.apply_match_result(text, int, boolean) to authenticated;

-- Geriye dönük uyumluluk: eski zafer RPC'si yeni mantığa yönlendirir
create or replace function public.record_universe_victory(p_room_type text default 'normal')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.apply_match_result(p_room_type, 1, false);
end;
$$;

grant execute on function public.record_universe_victory(text) to authenticated;

-- -----------------------------------------------------------------------------
-- 7) REALTIME (Postgres Changes — profil & skor dinleme)
--    Dashboard: Database → Publications → supabase_realtime
-- -----------------------------------------------------------------------------

do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.leaderboard;
exception
  when duplicate_object then null;
end $$;

-- -----------------------------------------------------------------------------
-- 8) İNDEKSLER (performans)
-- -----------------------------------------------------------------------------

create index if not exists leaderboard_max_mass_desc_idx
  on public.leaderboard (max_mass desc);

create index if not exists profiles_diamonds_desc_idx
  on public.profiles (diamonds desc, games_won desc);

-- Benzersiz kullanıcı adı (büyük/küçük harf duyarsız)
create unique index if not exists profiles_username_lower_key
  on public.profiles (lower(trim(username)))
  where username is not null and trim(username) <> '';

-- -----------------------------------------------------------------------------
-- 9) PROFİL GÜNCELLEME RPC (benzersiz isim kontrolü)
-- -----------------------------------------------------------------------------

create or replace function public.update_player_profile(
  p_username text,
  p_avatar_url text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trimmed text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  v_trimmed := trim(p_username);

  if char_length(v_trimmed) < 3 or char_length(v_trimmed) > 12 then
    raise exception 'invalid_username_length';
  end if;

  if exists (
    select 1 from public.profiles
    where lower(trim(username)) = lower(v_trimmed)
      and id <> auth.uid()
  ) then
    raise exception 'username_taken';
  end if;

  update public.profiles
  set
    username = v_trimmed,
    avatar_url = coalesce(p_avatar_url, avatar_url),
    updated_at = timezone('utc', now())
  where id = auth.uid();

  update public.leaderboard
  set username = v_trimmed, updated_at = timezone('utc', now())
  where user_id = auth.uid();
end;
$$;

grant execute on function public.update_player_profile(text, text) to authenticated;

-- -----------------------------------------------------------------------------
-- 10) AVATAR DEPOLAMA (Supabase Storage)
--     Dashboard: Storage → avatars bucket otomatik oluşur
-- -----------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Avatar görselleri herkese açık" on storage.objects;
create policy "Avatar görselleri herkese açık"
  on storage.objects for select
  using (bucket_id = 'avatars');

drop policy if exists "Kullanıcı kendi avatarını yükleyebilir" on storage.objects;
create policy "Kullanıcı kendi avatarını yükleyebilir"
  on storage.objects for insert
  with check (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Kullanıcı kendi avatarını güncelleyebilir" on storage.objects;
create policy "Kullanıcı kendi avatarını güncelleyebilir"
  on storage.objects for update
  using (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

drop policy if exists "Kullanıcı kendi avatarını silebilir" on storage.objects;
create policy "Kullanıcı kendi avatarını silebilir"
  on storage.objects for delete
  using (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- -----------------------------------------------------------------------------
-- 11) ODA ÖRNEKLERİ & MATCHMAKING (ayrıntı: migration_game_rooms.sql)
-- -----------------------------------------------------------------------------
